### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by MrPacha23** [Fallen-Breath/DiggyScoreboard#1]
Update this please, it was quite useful and now nothing like that can be found for multiplayer servers in new versions

**Comment by Fallen-Breath** [comment]
It already works in all new versions, what do you want for update?

**Comment by MrPacha23** [comment]
Really? I try to use them in my server 1.20.4 and it didn't work

**Comment by Fallen-Breath** [comment]
It works in my vanilla 1.20.4 setup

**Comment by MrPacha23** [comment]
This works with fabric servers?

**Comment by Fallen-Breath** [comment]
No one knows if your server is modded too much

**Comment by MrPacha23** [comment]
No, i only have lithium and carpet mods
