### ISSUE TITLE
Because of the legacy datapack directory names have been renamed, it cannot be used in minecraft 1.21

### ISSUE THREAD

**Issue by DreamingLri** [Fallen-Breath/DiggyScoreboard#3]
Because of the legacy datapack directory names have been renamed, it cannot be used in minecraft 1.21

Please rename the folder `DiggyScoreboard\data\diggy\functions` to `DiggyScoreboard\data\diggy\function` in order to make this datapack can be used in minecraft 1.21

Thanks awa

**Comment by Fallen-Breath** [comment]
I'll need to somehow refactor this repos to avoid git branches spams before fixing this

**Comment by Fallen-Breath** [comment]
resolved in v1.1
